# Generated by Django 4.2.20 on 2025-03-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='hashtags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='title',
            field=models.CharField(default='Untitled Post', max_length=255),
        ),
    ]
