# Generated by Django 4.2.20 on 2025-03-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_communitypost_hashtags_communitypost_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='hashtags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
