# Generated by Django 4.2.20 on 2025-03-21 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_text_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
