# Generated by Django 4.2.20 on 2025-03-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_pantryitem_last_used_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
