# Generated by Django 4.2.20 on 2025-03-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_recipe_cuisines_recipe_dietary_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
