# Generated by Django 4.2.20 on 2025-03-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Dairy', 'Dairy'), ('Meat', 'Meat'), ('Vegetables', 'Vegetables'), ('Grains', 'Grains'), ('Fruits', 'Fruits'), ('Others', 'Others')], default='Others', max_length=100),
        ),
    ]
