# Generated by Django 4.2.20 on 2025-03-21 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_usagelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usagelog',
            name='used_at',
        ),
        migrations.AddField(
            model_name='usagelog',
            name='quantity_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
